const users = [
  {
    firstName: "admin",
    lastName: "admin",
    email: "admin@gmail.com",
    password: "admin123",
    role: "admin",
    books: [],
    wishlist: [],
    orders: [
      {
        id: 1,
        title: "Castle In The Sky",
        author: "Hayao Miyazaki",
        price: 16.99,
        category: "Adventure",
        image: "../assets/home/book-1.png",
        description:
          "Vestibulum consectetur fringilla tellus, et pulvinar massa tempus nec. Fusce nibh nibh, consectetur vitae felis quis, sagittis ullamcorper enim. Nullam maximus vehicula justo, vel vestibulum turpis dictum at. Nam sed laoreet sem.",
        rating: 4.7,
        sold: 160,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 2,
        title: "Simple Things You Can Do to Save the Earth",
        author: "Stephen King",
        price: 29.99,
        category: "Adventure",
        image: "../assets/home/book-2.png",
        description:
          "A practical guide with actionable steps for environmental conservation and grassroots movements.",
        rating: 4.5,
        sold: 120,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 3,
        title: "Flovely And Unicom Erna",
        author: "Agatha Christie",
        price: 18.99,
        category: "Novels",
        image: "../assets/home/book-3.png",
        description:
          "A children's activity book categorized under kids’ literature, published in 2014.",
        rating: 4.2,
        sold: 90,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 4,
        title: "Qple Gpod with Retina Sisplay",
        author: "Dan Brown",
        price: 39.99,
        category: "Novels",
        image: "../assets/home/book-4.png",
        description:
          "Explores Apple's Retina Display technology introduced in 2010 and its visual clarity.",
        rating: 4.1,
        sold: 75,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 5,
        title: "The Alchemist",
        author: "Paulo Coelho",
        price: 14.99,
        category: "Philosophy",
        image: "../assets/home/book-5.png",
        description:
          "A journey of self-discovery through the deserts of Egypt.",
        isFeatured: false,
        rating: 4.7,
        sold: 150,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 6,
        title: "1984",
        author: "George Orwell",
        price: 12.5,
        category: "Dystopia",
        image: "../assets/home/book-6.png",
        description: "A chilling vision of a totalitarian future.",
        isFeatured: false,
        rating: 4.9,
        sold: 200,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 7,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        price: 11.75,
        category: "Classic",
        image: "../assets/home/book-7.jpeg",
        description: "A deep look into racial injustice and childhood.",
        isFeatured: false,
        rating: 4.8,
        sold: 180,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
    ],
  },
  {
    firstName: "Ahmed",
    lastName: "marwan",
    email: "ahmedmarwan200@gmail.com",
    password: "ahmed123",
    role: "customer",
    books: [],
    wishlist: [
      {
        id: 1,
        title: "Castle In The Sky",
        author: "Hayao Miyazaki",
        price: 16.99,
        category: "Adventure",
        image: "../assets/home/book-1.png",
        description:
          "Vestibulum consectetur fringilla tellus, et pulvinar massa tempus nec. Fusce nibh nibh, consectetur vitae felis quis, sagittis ullamcorper enim. Nullam maximus vehicula justo, vel vestibulum turpis dictum at. Nam sed laoreet sem.",
        rating: 4.7,
        sold: 160,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 2,
        title: "Simple Things You Can Do to Save the Earth",
        author: "Stephen King",
        price: 29.99,
        category: "Adventure",
        image: "../assets/home/book-2.png",
        description:
          "A practical guide with actionable steps for environmental conservation and grassroots movements.",
        rating: 4.5,
        sold: 120,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 3,
        title: "Flovely And Unicom Erna",
        author: "Agatha Christie",
        price: 18.99,
        category: "Novels",
        image: "../assets/home/book-3.png",
        description:
          "A children's activity book categorized under kids’ literature, published in 2014.",
        rating: 4.2,
        sold: 90,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 4,
        title: "Qple Gpod with Retina Sisplay",
        author: "Dan Brown",
        price: 39.99,
        category: "Novels",
        image: "../assets/home/book-4.png",
        description:
          "Explores Apple's Retina Display technology introduced in 2010 and its visual clarity.",
        rating: 4.1,
        sold: 75,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 5,
        title: "The Alchemist",
        author: "Paulo Coelho",
        price: 14.99,
        category: "Philosophy",
        image: "../assets/home/book-5.png",
        description: "A journey of self-discovery through the deserts of Egypt.",
        isFeatured: false,
        rating: 4.7,
        sold: 150,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 6,
        title: "1984",
        author: "George Orwell",
        price: 12.5,
        category: "Dystopia",
        image: "../assets/home/book-6.png",
        description: "A chilling vision of a totalitarian future.",
        isFeatured: false,
        rating: 4.9,
        sold: 200,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 7,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        price: 11.75,
        category: "Classic",
        image: "../assets/home/book-7.jpeg",
        description: "A deep look into racial injustice and childhood.",
        isFeatured: false,
        rating: 4.8,
        sold: 180,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
    ],
    orders: [
      {
        id: 1,
        title: "Castle In The Sky",
        author: "Hayao Miyazaki",
        price: 16.99,
        category: "Adventure",
        image: "../assets/home/book-1.png",
        description:
          "Vestibulum consectetur fringilla tellus, et pulvinar massa tempus nec. Fusce nibh nibh, consectetur vitae felis quis, sagittis ullamcorper enim. Nullam maximus vehicula justo, vel vestibulum turpis dictum at. Nam sed laoreet sem.",
        rating: 4.7,
        sold: 160,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 2,
        title: "Simple Things You Can Do to Save the Earth",
        author: "Stephen King",
        price: 29.99,
        category: "Adventure",
        image: "../assets/home/book-2.png",
        description:
          "A practical guide with actionable steps for environmental conservation and grassroots movements.",
        rating: 4.5,
        sold: 120,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 3,
        title: "Flovely And Unicom Erna",
        author: "Agatha Christie",
        price: 18.99,
        category: "Novels",
        image: "../assets/home/book-3.png",
        description:
          "A children's activity book categorized under kids’ literature, published in 2014.",
        rating: 4.2,
        sold: 90,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 4,
        title: "Qple Gpod with Retina Sisplay",
        author: "Dan Brown",
        price: 39.99,
        category: "Novels",
        image: "../assets/home/book-4.png",
        description:
          "Explores Apple's Retina Display technology introduced in 2010 and its visual clarity.",
        rating: 4.1,
        sold: 75,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 5,
        title: "The Alchemist",
        author: "Paulo Coelho",
        price: 14.99,
        category: "Philosophy",
        image: "../assets/home/book-5.png",
        description: "A journey of self-discovery through the deserts of Egypt.",
        isFeatured: false,
        rating: 4.7,
        sold: 150,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 6,
        title: "1984",
        author: "George Orwell",
        price: 12.5,
        category: "Dystopia",
        image: "../assets/home/book-6.png",
        description: "A chilling vision of a totalitarian future.",
        isFeatured: false,
        rating: 4.9,
        sold: 200,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 7,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        price: 11.75,
        category: "Classic",
        image: "../assets/home/book-7.jpeg",
        description: "A deep look into racial injustice and childhood.",
        isFeatured: false,
        rating: 4.8,
        sold: 180,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
    ],
  },
  {
    firstName: "Asmaa",
    lastName: "mousaa",
    email: "asmaamousa200@gmail.com",
    password: "asmaa123",
    role: "customer",
    books: [],
    wishlist: [
      {
        id: 1,
        title: "Castle In The Sky",
        author: "Hayao Miyazaki",
        price: 16.99,
        category: "Adventure",
        image: "../assets/home/book-1.png",
        description:
          "Vestibulum consectetur fringilla tellus, et pulvinar massa tempus nec. Fusce nibh nibh, consectetur vitae felis quis, sagittis ullamcorper enim. Nullam maximus vehicula justo, vel vestibulum turpis dictum at. Nam sed laoreet sem.",
        rating: 4.7,
        sold: 160,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 2,
        title: "Simple Things You Can Do to Save the Earth",
        author: "Stephen King",
        price: 29.99,
        category: "Adventure",
        image: "../assets/home/book-2.png",
        description:
          "A practical guide with actionable steps for environmental conservation and grassroots movements.",
        rating: 4.5,
        sold: 120,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 3,
        title: "Flovely And Unicom Erna",
        author: "Agatha Christie",
        price: 18.99,
        category: "Novels",
        image: "../assets/home/book-3.png",
        description:
          "A children's activity book categorized under kids’ literature, published in 2014.",
        rating: 4.2,
        sold: 90,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 4,
        title: "Qple Gpod with Retina Sisplay",
        author: "Dan Brown",
        price: 39.99,
        category: "Novels",
        image: "../assets/home/book-4.png",
        description:
          "Explores Apple's Retina Display technology introduced in 2010 and its visual clarity.",
        rating: 4.1,
        sold: 75,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 5,
        title: "The Alchemist",
        author: "Paulo Coelho",
        price: 14.99,
        category: "Philosophy",
        image: "../assets/home/book-5.png",
        description: "A journey of self-discovery through the deserts of Egypt.",
        isFeatured: false,
        rating: 4.7,
        sold: 150,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 6,
        title: "1984",
        author: "George Orwell",
        price: 12.5,
        category: "Dystopia",
        image: "../assets/home/book-6.png",
        description: "A chilling vision of a totalitarian future.",
        isFeatured: false,
        rating: 4.9,
        sold: 200,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 7,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        price: 11.75,
        category: "Classic",
        image: "../assets/home/book-7.jpeg",
        description: "A deep look into racial injustice and childhood.",
        isFeatured: false,
        rating: 4.8,
        sold: 180,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
    ],
    orders: [
      {
        id: 1,
        title: "Castle In The Sky",
        author: "Hayao Miyazaki",
        price: 16.99,
        category: "Adventure",
        image: "../assets/home/book-1.png",
        description:
          "Vestibulum consectetur fringilla tellus, et pulvinar massa tempus nec. Fusce nibh nibh, consectetur vitae felis quis, sagittis ullamcorper enim. Nullam maximus vehicula justo, vel vestibulum turpis dictum at. Nam sed laoreet sem.",
        rating: 4.7,
        sold: 160,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 2,
        title: "Simple Things You Can Do to Save the Earth",
        author: "Stephen King",
        price: 29.99,
        category: "Adventure",
        image: "../assets/home/book-2.png",
        description:
          "A practical guide with actionable steps for environmental conservation and grassroots movements.",
        rating: 4.5,
        sold: 120,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 3,
        title: "Flovely And Unicom Erna",
        author: "Agatha Christie",
        price: 18.99,
        category: "Novels",
        image: "../assets/home/book-3.png",
        description:
          "A children's activity book categorized under kids’ literature, published in 2014.",
        rating: 4.2,
        sold: 90,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 4,
        title: "Qple Gpod with Retina Sisplay",
        author: "Dan Brown",
        price: 39.99,
        category: "Novels",
        image: "../assets/home/book-4.png",
        description:
          "Explores Apple's Retina Display technology introduced in 2010 and its visual clarity.",
        rating: 4.1,
        sold: 75,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 5,
        title: "The Alchemist",
        author: "Paulo Coelho",
        price: 14.99,
        category: "Philosophy",
        image: "../assets/home/book-5.png",
        description: "A journey of self-discovery through the deserts of Egypt.",
        isFeatured: false,
        rating: 4.7,
        sold: 150,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 6,
        title: "1984",
        author: "George Orwell",
        price: 12.5,
        category: "Dystopia",
        image: "../assets/home/book-6.png",
        description: "A chilling vision of a totalitarian future.",
        isFeatured: false,
        rating: 4.9,
        sold: 200,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 7,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        price: 11.75,
        category: "Classic",
        image: "../assets/home/book-7.jpeg",
        description: "A deep look into racial injustice and childhood.",
        isFeatured: false,
        rating: 4.8,
        sold: 180,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
    ],
  },
  {
    firstName: "Abelrahman",
    lastName: "Necro",
    email: "abdelrahman200@gmail.com",
    password: "Abelrahman123",
    role: "customer",
    books: [],
    wishlist: [
      {
        id: 1,
        title: "Castle In The Sky",
        author: "Hayao Miyazaki",
        price: 16.99,
        category: "Adventure",
        image: "../assets/home/book-1.png",
        description:
          "Vestibulum consectetur fringilla tellus, et pulvinar massa tempus nec. Fusce nibh nibh, consectetur vitae felis quis, sagittis ullamcorper enim. Nullam maximus vehicula justo, vel vestibulum turpis dictum at. Nam sed laoreet sem.",
        rating: 4.7,
        sold: 160,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 2,
        title: "Simple Things You Can Do to Save the Earth",
        author: "Stephen King",
        price: 29.99,
        category: "Adventure",
        image: "../assets/home/book-2.png",
        description:
          "A practical guide with actionable steps for environmental conservation and grassroots movements.",
        rating: 4.5,
        sold: 120,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 3,
        title: "Flovely And Unicom Erna",
        author: "Agatha Christie",
        price: 18.99,
        category: "Novels",
        image: "../assets/home/book-3.png",
        description:
          "A children's activity book categorized under kids’ literature, published in 2014.",
        rating: 4.2,
        sold: 90,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 4,
        title: "Qple Gpod with Retina Sisplay",
        author: "Dan Brown",
        price: 39.99,
        category: "Novels",
        image: "../assets/home/book-4.png",
        description:
          "Explores Apple's Retina Display technology introduced in 2010 and its visual clarity.",
        rating: 4.1,
        sold: 75,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 5,
        title: "The Alchemist",
        author: "Paulo Coelho",
        price: 14.99,
        category: "Philosophy",
        image: "../assets/home/book-5.png",
        description: "A journey of self-discovery through the deserts of Egypt.",
        isFeatured: false,
        rating: 4.7,
        sold: 150,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 6,
        title: "1984",
        author: "George Orwell",
        price: 12.5,
        category: "Dystopia",
        image: "../assets/home/book-6.png",
        description: "A chilling vision of a totalitarian future.",
        isFeatured: false,
        rating: 4.9,
        sold: 200,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 7,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        price: 11.75,
        category: "Classic",
        image: "../assets/home/book-7.jpeg",
        description: "A deep look into racial injustice and childhood.",
        isFeatured: false,
        rating: 4.8,
        sold: 180,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
    ],
    orders: [
      {
        id: 1,
        title: "Castle In The Sky",
        author: "Hayao Miyazaki",
        price: 16.99,
        category: "Adventure",
        image: "../assets/home/book-1.png",
        description:
          "Vestibulum consectetur fringilla tellus, et pulvinar massa tempus nec. Fusce nibh nibh, consectetur vitae felis quis, sagittis ullamcorper enim. Nullam maximus vehicula justo, vel vestibulum turpis dictum at. Nam sed laoreet sem.",
        rating: 4.7,
        sold: 160,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 2,
        title: "Simple Things You Can Do to Save the Earth",
        author: "Stephen King",
        price: 29.99,
        category: "Adventure",
        image: "../assets/home/book-2.png",
        description:
          "A practical guide with actionable steps for environmental conservation and grassroots movements.",
        rating: 4.5,
        sold: 120,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 3,
        title: "Flovely And Unicom Erna",
        author: "Agatha Christie",
        price: 18.99,
        category: "Novels",
        image: "../assets/home/book-3.png",
        description:
          "A children's activity book categorized under kids’ literature, published in 2014.",
        rating: 4.2,
        sold: 90,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 4,
        title: "Qple Gpod with Retina Sisplay",
        author: "Dan Brown",
        price: 39.99,
        category: "Novels",
        image: "../assets/home/book-4.png",
        description:
          "Explores Apple's Retina Display technology introduced in 2010 and its visual clarity.",
        rating: 4.1,
        sold: 75,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 5,
        title: "The Alchemist",
        author: "Paulo Coelho",
        price: 14.99,
        category: "Philosophy",
        image: "../assets/home/book-5.png",
        description: "A journey of self-discovery through the deserts of Egypt.",
        isFeatured: false,
        rating: 4.7,
        sold: 150,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 6,
        title: "1984",
        author: "George Orwell",
        price: 12.5,
        category: "Dystopia",
        image: "../assets/home/book-6.png",
        description: "A chilling vision of a totalitarian future.",
        isFeatured: false,
        rating: 4.9,
        sold: 200,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 7,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        price: 11.75,
        category: "Classic",
        image: "../assets/home/book-7.jpeg",
        description: "A deep look into racial injustice and childhood.",
        isFeatured: false,
        rating: 4.8,
        sold: 180,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
    ],
  },
  {
    firstName: "Amira",
    lastName: "Mahmoud",
    email: "amiramahmoud200@gmail.com",
    password: "amira123",
    role: "seller",
    books: [
      {
        id: 1,
        title: "Castle In The Sky",
        author: "Hayao Miyazaki",
        price: 16.99,
        category: "Adventure",
        image: "../assets/home/book-1.png",
        description:
          "Vestibulum consectetur fringilla tellus, et pulvinar massa tempus nec. Fusce nibh nibh, consectetur vitae felis quis, sagittis ullamcorper enim. Nullam maximus vehicula justo, vel vestibulum turpis dictum at. Nam sed laoreet sem.",
        rating: 4.7,
        sold: 160,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 2,
        title: "Simple Things You Can Do to Save the Earth",
        author: "Stephen King",
        price: 29.99,
        category: "Adventure",
        image: "../assets/home/book-2.png",
        description:
          "A practical guide with actionable steps for environmental conservation and grassroots movements.",
        rating: 4.5,
        sold: 120,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 3,
        title: "Flovely And Unicom Erna",
        author: "Agatha Christie",
        price: 18.99,
        category: "Novels",
        image: "../assets/home/book-3.png",
        description:
          "A children's activity book categorized under kids’ literature, published in 2014.",
        rating: 4.2,
        sold: 90,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 4,
        title: "Qple Gpod with Retina Sisplay",
        author: "Dan Brown",
        price: 39.99,
        category: "Novels",
        image: "../assets/home/book-4.png",
        description:
          "Explores Apple's Retina Display technology introduced in 2010 and its visual clarity.",
        rating: 4.1,
        sold: 75,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 5,
        title: "The Alchemist",
        author: "Paulo Coelho",
        price: 14.99,
        category: "Philosophy",
        image: "../assets/home/book-5.png",
        description:
          "A journey of self-discovery through the deserts of Egypt.",
        isFeatured: false,
        rating: 4.7,
        sold: 150,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 6,
        title: "1984",
        author: "George Orwell",
        price: 12.5,
        category: "Dystopia",
        image: "../assets/home/book-6.png",
        description: "A chilling vision of a totalitarian future.",
        isFeatured: false,
        rating: 4.9,
        sold: 200,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 7,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        price: 11.75,
        category: "Classic",
        image: "../assets/home/book-7.jpeg",
        description: "A deep look into racial injustice and childhood.",
        isFeatured: false,
        rating: 4.8,
        sold: 180,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
    ],
    wishlist: [],
    orders: [
      {
        id: 1,
        title: "Castle In The Sky",
        author: "Hayao Miyazaki",
        price: 16.99,
        category: "Adventure",
        image: "../assets/home/book-1.png",
        description:
          "Vestibulum consectetur fringilla tellus, et pulvinar massa tempus nec. Fusce nibh nibh, consectetur vitae felis quis, sagittis ullamcorper enim. Nullam maximus vehicula justo, vel vestibulum turpis dictum at. Nam sed laoreet sem.",
        rating: 4.7,
        sold: 160,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 2,
        title: "Simple Things You Can Do to Save the Earth",
        author: "Stephen King",
        price: 29.99,
        category: "Adventure",
        image: "../assets/home/book-2.png",
        description:
          "A practical guide with actionable steps for environmental conservation and grassroots movements.",
        rating: 4.5,
        sold: 120,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 3,
        title: "Flovely And Unicom Erna",
        author: "Agatha Christie",
        price: 18.99,
        category: "Novels",
        image: "../assets/home/book-3.png",
        description:
          "A children's activity book categorized under kids’ literature, published in 2014.",
        rating: 4.2,
        sold: 90,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 4,
        title: "Qple Gpod with Retina Sisplay",
        author: "Dan Brown",
        price: 39.99,
        category: "Novels",
        image: "../assets/home/book-4.png",
        description:
          "Explores Apple's Retina Display technology introduced in 2010 and its visual clarity.",
        rating: 4.1,
        sold: 75,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 5,
        title: "The Alchemist",
        author: "Paulo Coelho",
        price: 14.99,
        category: "Philosophy",
        image: "../assets/home/book-5.png",
        description:
          "A journey of self-discovery through the deserts of Egypt.",
        isFeatured: false,
        rating: 4.7,
        sold: 150,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
    ],
  },
  {
    firstName: "Mohamed",
    lastName: "Hamdy",
    email: "mohamedhamdy200@gmail.com",
    password: "mohamed123",
    role: "seller",
    books: [
      {
        id: 1,
        title: "Castle In The Sky",
        author: "Hayao Miyazaki",
        price: 16.99,
        category: "Adventure",
        image: "../assets/home/book-1.png",
        description:
          "Vestibulum consectetur fringilla tellus, et pulvinar massa tempus nec. Fusce nibh nibh, consectetur vitae felis quis, sagittis ullamcorper enim. Nullam maximus vehicula justo, vel vestibulum turpis dictum at. Nam sed laoreet sem.",
        rating: 4.7,
        sold: 160,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 2,
        title: "Simple Things You Can Do to Save the Earth",
        author: "Stephen King",
        price: 29.99,
        category: "Adventure",
        image: "../assets/home/book-2.png",
        description:
          "A practical guide with actionable steps for environmental conservation and grassroots movements.",
        rating: 4.5,
        sold: 120,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 3,
        title: "Flovely And Unicom Erna",
        author: "Agatha Christie",
        price: 18.99,
        category: "Novels",
        image: "../assets/home/book-3.png",
        description:
          "A children's activity book categorized under kids’ literature, published in 2014.",
        rating: 4.2,
        sold: 90,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 4,
        title: "Qple Gpod with Retina Sisplay",
        author: "Dan Brown",
        price: 39.99,
        category: "Novels",
        image: "../assets/home/book-4.png",
        description:
          "Explores Apple's Retina Display technology introduced in 2010 and its visual clarity.",
        rating: 4.1,
        sold: 75,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 5,
        title: "The Alchemist",
        author: "Paulo Coelho",
        price: 14.99,
        category: "Philosophy",
        image: "../assets/home/book-5.png",
        description:
          "A journey of self-discovery through the deserts of Egypt.",
        isFeatured: false,
        rating: 4.7,
        sold: 150,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 6,
        title: "1984",
        author: "George Orwell",
        price: 12.5,
        category: "Dystopia",
        image: "../assets/home/book-6.png",
        description: "A chilling vision of a totalitarian future.",
        isFeatured: false,
        rating: 4.9,
        sold: 200,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 7,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        price: 11.75,
        category: "Classic",
        image: "../assets/home/book-7.jpeg",
        description: "A deep look into racial injustice and childhood.",
        isFeatured: false,
        rating: 4.8,
        sold: 180,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
    ],
    wishlist: [],
    orders: [
      {
        id: 1,
        title: "Castle In The Sky",
        author: "Hayao Miyazaki",
        price: 16.99,
        category: "Adventure",
        image: "../assets/home/book-1.png",
        description:
          "Vestibulum consectetur fringilla tellus, et pulvinar massa tempus nec. Fusce nibh nibh, consectetur vitae felis quis, sagittis ullamcorper enim. Nullam maximus vehicula justo, vel vestibulum turpis dictum at. Nam sed laoreet sem.",
        rating: 4.7,
        sold: 160,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 2,
        title: "Simple Things You Can Do to Save the Earth",
        author: "Stephen King",
        price: 29.99,
        category: "Adventure",
        image: "../assets/home/book-2.png",
        description:
          "A practical guide with actionable steps for environmental conservation and grassroots movements.",
        rating: 4.5,
        sold: 120,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 3,
        title: "Flovely And Unicom Erna",
        author: "Agatha Christie",
        price: 18.99,
        category: "Novels",
        image: "../assets/home/book-3.png",
        description:
          "A children's activity book categorized under kids’ literature, published in 2014.",
        rating: 4.2,
        sold: 90,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 4,
        title: "Qple Gpod with Retina Sisplay",
        author: "Dan Brown",
        price: 39.99,
        category: "Novels",
        image: "../assets/home/book-4.png",
        description:
          "Explores Apple's Retina Display technology introduced in 2010 and its visual clarity.",
        rating: 4.1,
        sold: 75,
        isFeatured: false,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
      {
        id: 5,
        title: "The Alchemist",
        author: "Paulo Coelho",
        price: 14.99,
        category: "Philosophy",
        image: "../assets/home/book-5.png",
        description:
          "A journey of self-discovery through the deserts of Egypt.",
        isFeatured: false,
        rating: 4.7,
        sold: 150,
        stock: 25,
        isTopCategories: true,
        isTopBooks: true,
        isTopRating: true,
      },
    ],
  },
];

if (!localStorage.getItem("users")) {
  localStorage.setItem("users", JSON.stringify(users));
}
